# Cloud Build configuration for Admin Dashboard
steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/admin-dashboard:$COMMIT_SHA',
      '-t', 'gcr.io/$PROJECT_ID/admin-dashboard:latest',
      '.'
    ]
    dir: 'admin-dashboard'

  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/admin-dashboard:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/admin-dashboard:latest']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'run', 'deploy', 'admin-dashboard',
      '--image', 'gcr.io/$PROJECT_ID/admin-dashboard:$COMMIT_SHA',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--port', '8080',
      '--memory', '512Mi',
      '--cpu', '1',
      '--min-instances', '0',
      '--max-instances', '10',
      '--concurrency', '1000',
      '--timeout', '300',
      '--set-env-vars', 'NODE_ENV=production',
      '--set-env-vars', 'VITE_API_BASE_URL=https://api.curk.in/api/v1',
      '--set-env-vars', 'VITE_USE_API_KEY=false'
    ]

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/admin-dashboard:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/admin-dashboard:latest'

# Build options
options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 100
  logging: CLOUD_LOGGING_ONLY

# Timeout for the entire build
timeout: '1200s'
